name: AutomatedGPUTests

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        julia-version: ['1.7.3','1.8.2']
    
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - run: export JULIA_DEPOT_PATH="/home/rjeyaram/actions-runner"
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
